In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/Retail_Dataset_Modified.csv")
print("Dataset Loaded Successfully")

Dataset Loaded Successfully


In [3]:
sales_matrix = np.array(df[['Revenue', 'Units_Sold']])
print(sales_matrix)

[['7320' '24']
 ['1645' '35']
 ['66340' '31']
 ...
 ['982202' '13']
 ['244244' '22']
 ['1408680' '12']]


In [4]:
print("Matrix Shape:")
print(sales_matrix.shape)

Matrix Shape:
(5171, 2)


In [5]:
transpose_matrix = sales_matrix.T

print("Transpose Matrix:")
print(transpose_matrix)

Transpose Matrix:
[['7320' '1645' '66340' ... '982202' '244244' '1408680']
 ['24' '35' '31' ... '13' '22' '12']]


Reshape

In [6]:
sample_array = np.arange(1, 13)

print(sample_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
matrix_3x4 = sample_array.reshape(3,4)

print(matrix_3x4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
matrix_4x3 = sample_array.reshape(4,3)
print(matrix_4x3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
flat_array = matrix_3x4.flatten()
print(flat_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [11]:
revenue_values = np.array(df['Revenue'][:12])

revenue_matrix = revenue_values.reshape(3,4)

print(revenue_matrix)

[['7320' '1645' '66340' '77748']
 ['1976364' '18511' '3026641' '4860270']
 ['870570' '35552' '318948' '25636']]


In [12]:
print("Rows and Columns:")
print(revenue_matrix.shape)

Rows and Columns:
(3, 4)
